= 1. Introducción
<introducción>

== 1.1 Contexto Global y Panorama de Vulnerabilidades Web
<contexto-global-panorama-vulnerabilidades>

Las aplicaciones web constituyen uno de los pilares fundamentales de la infraestructura digital contemporánea. Organizaciones empresariales, organismos gubernamentales, instituciones académicas y plataformas de comercio electrónico gestionan volúmenes crecientes de información crítica y transaccional a través de sistemas accesibles públicamente mediante internet para interactuar de forma continua con usuarios finales.

Esta centralidad operativa tiene como contrapartida un incremento sistemático en la superficie de ataque y el volumen de incidentes informáticos. De acuerdo con el _2025 Data Breach Investigations Report_ \(DBIR) de Verizon, los ataques dirigidos a aplicaciones web \(_Basic Web Application Attacks_\) representaron el 12% del total de brechas de seguridad confirmadas a nivel global durante 2025, experimentando un ascenso frente al 9% registrado en el período precedente, con el agravante de que el 88% de estos incidentes involucró el uso indebido de credenciales comprometidas \(Verizon, 2025). En consonancia, el informe _Cost of a Data Breach Report 2025_ elaborado por IBM sitúa el costo económico promedio global de una vulneración de datos en 4,44 millones de dólares \(IBM, 2025). Estos indicadores cuantitativos evidencian que la debilidad en los perímetros web no constituye un problema periférico, sino un vector de riesgo crítico de elevado impacto patrimonial y reputacional.

Entre las fallas de seguridad recurrentes en los ecosistemas web destacan la inyección de código SQL, las secuencias de comandos en sitios cruzados \(Cross-Site Scripting o XSS), las configuraciones de seguridad defectuosas o permisivas, los mecanismos de autenticación y gestión de sesiones débiles, y la exposición involuntaria de rutas o servicios internos. Estas amenazas se encuentran ampliamente categorizadas por la comunidad técnica internacional a través del estándar del proyecto _Open Web Application Security Project_ \(OWASP Top 10, 2021), que establece el consenso sobre los riesgos más severos a los que se enfrentan las arquitecturas web modernas.

== 1.2 La Necesidad de Orquestación: Paradigma SOAR y Enfoque DAST Integrado
<necesidad-orquestacion-soar-dast>

Frente a este escenario, la evaluación de seguridad tradicional recurre a dos modalidades primarias: auditorías manuales conducidas por analistas de penetración o la utilización aislada de herramientas automatizadas de escaneo dinámico \(DAST, _Dynamic Application Security Testing_\). El enfoque DAST permite examinar las aplicaciones en su estado de ejecución sin requerir acceso al código fuente, analizando el comportamiento de entradas y respuestas frente a solicitudes anómalas \(Qadir et al., 2025). Sin embargo, el empleo independiente y descoordinado de escáneres dinámicos introduce fricciones operativas notables: demanda una intervención humana reiterativa para la parametrización de cada consola, adolece de formatos de salida dispares que dificultan la consolidación de hallazgos y exige una ardua labor de correlación manual para filtrar falsos positivos o reconstruir el cuadro integral de riesgos.

Con el propósito de mitigar esta sobrecarga y dotar de agilidad al diagnóstico, surge en la industria el paradigma SOAR \(_Security Orchestration, Automation and Response_\), orientado a la orquestación de herramientas heterogéneas, la automatización de flujos repetitivos y la centralización de los reportes de incidentes \(Kinyua & Awuah, 2021). No obstante, como se analiza en el Capítulo 7 \(Estado del Arte), las plataformas de referencia en este ámbito —tales como Faraday, DefectDojo, TheHive o Shuffle— presentan una marcada orientación hacia la gestión agregada a nivel corporativo o demandan una infraestructura de soporte y consumo de recursos considerablemente pesada \(ver Tabla 1). Emerge así una vacancia técnica específica: la necesidad de una solución de orquestación ágil, desacoplada y liviana, que combine el escaneo dinámico general con técnicas de fuzzing activo y explotación dirigida, empaquetada de manera integral bajo contenedores Docker Compose de despliegue directo.

Para abordar dicha brecha, este proyecto implementa un pipeline articulado sobre tres herramientas complementarias de código abierto: OWASP ZAP, que realiza un escaneo dinámico de propósito general \(en sus fases pasiva y activa); ffuf, especializado en el descubrimiento de superficie oculta mediante _fuzzing_ de alta velocidad sobre directorios y rutas web \(Alsaedi et al., 2021); y SQLMap, orientado de manera especializada a la detección profunda y verificación de explotación sobre vulnerabilidades de inyección SQL \(Elia et al., 2010), un vector que los escáneres generalistas suelen subestimar o diagnosticar con menor alcance. La combinación estratégica de estas tres capas —descubrimiento de rutas no enlazadas, análisis transversal de vulnerabilidades y verificación exhaustiva de inyecciones— permite maximizar la cobertura global del diagnóstico sin incurrir en la sobrecarga operativa de las plataformas empresariales complejas.

== 1.3 Propuesta de Valor, Alcance del Prototipo y Entorno Experimental
<propuesta-valor-alcance-prototipo>

En este marco metodológico y tecnológico, el presente trabajo final tiene por objetivo diseñar, implementar y validar un orquestador automatizado de herramientas de seguridad web capaz de ejecutar análisis dinámicos secuenciales, normalizar los esquemas sintácticos heterogéneos de cada componente y consolidar un reporte unificado de hallazgos. A partir de dicho núcleo de ejecución por consola, el sistema fue escalado hacia una arquitectura de servicio completa: una API REST asíncrona desarrollada en FastAPI que administra los análisis en segundo plano, persiste el historial de auditorías en base de datos relacional, implementa un módulo de autenticación automatizada para examinar secciones protegidas tras mecanismos de login, proporciona sugerencias de remediación estructuradas mediante inteligencia artificial y expone los resultados a través de un panel web interactivo para el analista.

A efectos de garantizar el rigor metodológico, la reproducibilidad de los ensayos y un marco deontológico estricto, el sistema fue sometido a validación experimental sobre la plataforma vulnerable deliberada _Damn Vulnerable Web Application_ \(DVWA) desplegada en un entorno de red Docker aislado. Dicho esquema garantiza el pleno cumplimiento de la legislación nacional sobre delitos informáticos \(Ley 26.388) y los principios éticos internacionales de la profesión \(Código de Ética ACM), cuyas derivaciones jurídicas y operativas se examinan formalmente en el Capítulo 16.

== 1.4 Estructura del Documento
<estructura-del-documento>

El presente trabajo se encuentra articulado de la siguiente manera: las secciones 2 a 6 definen la problemática, justificación, metas, interrogantes e hipótesis orientadoras. Las bases teóricas y el estado del arte se examinan en las secciones 7 y 8, dando paso a la delimitación y metodología en los apartados 9 y 10. La arquitectura del sistema, el modelo de servicio y la implementación técnica del pipeline se detallan en los capítulos 11 y 12. La presentación de hallazgos y su debate técnico se abordan en las secciones 13 y 14, condensando las conclusiones y líneas de investigación futuras en el capítulo 15. Por último, la sección 16 aborda las consideraciones éticas y normativas, el capítulo 17 profundiza el desarrollo experimental y los apartados 18 y 19 reúnen las fuentes bibliográficas y anexos técnicos.
